# Specify the build of reference genome used (either 'GRCh37' or 'GRCh38')
BUILD: "GRCh38"

# Specify the type of input data (either 'Single' or 'Cohort')
DATA: "Single"

# File directories to reference genome, dbSNP database and various vcf annotation databases
REFGENOME: "/path/to/reference/human/genome/Homo_sapiens_assembly38.fasta.gz"
dbSNP: "/path/to/dbSNP/All_20180418.vcf.gz"
VEP: "/path/to/vep/GRCh38/"
dbNSFP: "/path/to/dbNSFP/dbNSFPv4.0a_custombuild.gz"
MILLS: "/path/to/Mills/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
SNP1000G: "/path/to/1000G/snps/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
OMNI: "/path/to/omni/1000G_omni2.5.hg38.vcf.gz"
HAPMAP: "/path/to/hapmap/hapmap_3.3.hg38.vcf.gz"
CADD: "/path/to/CADD/whole_genome_SNVs.tsv.gz"

# Temporary file directory
TEMPDIR: "/file/path/to/tmp/"

# Whole exome sequencing (WES) specific settings (leave blank if analysing other data such as WGS)
WES:
  # Genomic intervals over which to operate
  INTERVALS: ""
  # Amount of padding (in bp) to add to each interval you are including
  PADDING: ""

# Resources used to filter indels and SNP's
# Either call resources from databases defined above or provide a file directory
# Additional resources can be added
FILTERING:
  # Single sample analyses
  SINGLE: "--resource config['HAPMAP']
          --resource config['MILLS']"

  # Cohort analyses
  COHORT:
    INDELS: ""
    SNPS: ""