############################
##### Overall workflow #####
############################

# Run GPU accelerated where possible - big speed ups (either 'Yes' or 'No')
GPU: "No"

# Build of reference genome (either 'GRCh37' or 'GRCh38')
BUILD: "GRCh37"

# Type of input data (either 'Single' or 'Cohort')
DATA: "Cohort"

# File directories to reference genome and dbSNP database
REFGENOME: "/path/to/reference/human/genome/ucsc.hg19.fasta"
dbSNP: "/path/to/dbSNP/All_20180423.vcf.gz"

# Temporary file directory
TEMPDIR: "/file/path/to/tmp/"

# WES settings (leave blank if analysing other data such as WGS)
WES:
  # Genomic intervals over which to operate
  INTERVALS: "-L /path/to/regions/.bed"
  # Padding (in bp) to add to each interval
  PADDING: "-ip 100"

#############################
##### Variant filtering #####
#############################

# Resources used to filter indels and SNP's...
FILTERING:
  # ...for analysis of single samples
  SINGLE: ""

  # ...for analysis of cohorts
  COHORT:
    INDELS: "--resource:mills, known=false, training=true, truth=true, prior=12.0 /path/to/Mills/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz
            --resource:1000G, known=false, training=true, truth=false, prior=10.0 /path/to/1000G/indels/1000G_phase1.indels.hg19.sites.vcf.gz
            --resource:dbsnp, known=true, training=false, truth=false, prior=2.0 /path/to/dbSNP/All_20180423.vcf.gz"
    SNPS: "--resource:hapmap, known=false,training=true,truth=true,prior=15.0 /path/to/hapmap/hapmap_3.3.hg19.sites.vcf.gz
          --resource:omni, known=false,training=true,truth=false,prior=12.0 /path/to/omni/1000G_omni2.5.hg19.sites.vcf.gz
          --resource:1000G, known=false,training=true,truth=false,prior=10.0 /path/to/1000G/snps/1000G_phase1.snps.high_confidence.hg19.sites.vcf.gz
          --resource:dbsnp, known=true,training=false,truth=false,prior=2.0 /path/to/dbSNP/All_20180423.vcf.gz"

##########################
##### VCF annotation #####
##########################

# File directories to vcf annotation databases
VEP: "/path/to/vep/GRCh37/"
dbNSFP: "/path/to/dbNSFP/dbNSFPv4.0a.hg19.custombuild.gz"
CADD: "/path/to/CADD/whole_genome_SNVs.tsv.gz"